services:
  discord-bot:
    image: iziodev/spectre-tipper:v0.0.7
    volumes:
      - wallet-data:/spectre-tipper-wallets
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      SPECTRE_NETWORK: "mainnet"
      WALLET_DATA_PATH: "spectre-tipper-wallets"
      RUST_BACKTRACE: "full"
      FORCE_SPECTRE_NODE_ADDRESS: "ws://157.173.125.208:17210"

volumes:
  wallet-data:
